#!/bin/bash

. /etc/rc.d/init.d/functions

# Linux or MacOS: $ chmod 755 git-build

ARGS=$#
COMMIT=$1

function help {
  printf 'Use: git-build [commit]\n Example:
    git-build "init" \n'
}

if [ $ARGS != 1 ]; then
  help;
  exit;
fi

function selection {
  printf '$ npm run build... \n'
  npm run build;
  
  printf '\n$ git add dist -f...\n'
  git add dist -f;
  printf '\n$ git commit...\n';
  git commit -m "gh-pages: $1";

  printf '\n$ git subtree push --prefix dist origin gh-pages...\n';
  git subtree push --prefix dist origin gh-pages;
}

selection "$COMMIT"