#!/bin/bash

. /etc/rc.d/init.d/functions

# Linux or MacOS: $ chmod 755 git-build

ARGS=$#
COMMIT=$1

function help {
  printf 'Use: git-build [commit]\n Example:
    git-build "init" \n'
}

if [ $ARGS != 1 ]; then
  help;
  exit;
fi

function selection {
  echo "$ npm run build...\n";
  npm run build;
  
  echo "$ git add dist -f...\n";
  git add dist -f;
  echo "$ git commit...\n";
  git commit -m "$1";
  echo "$ git subtree push --prefix dist origin gh-pages...\n";
  git subtree push --prefix dist origin gh-pages;
}

selection "$COMMIT"